import Territory from "./territory"

const hoverColor = "red"
export const Territories = [
 new Territory('alaska', hoverColor),
 new Territory('northwest_territory', hoverColor),
 new Territory('eastern_australia', hoverColor),
 new Territory('indonesia', hoverColor),
 new Territory('new_guinea', hoverColor),
 new Territory('ontario', hoverColor),
 new Territory('venezuela', hoverColor),
 new Territory('madagascar', hoverColor),
 new Territory('north_africa', hoverColor),
 new Territory('greenland', hoverColor),
 new Territory('iceland', hoverColor),
 new Territory('great_britain', hoverColor),
 new Territory('scandinavia', hoverColor),
 new Territory('japan', hoverColor),
 new Territory('yakursk', hoverColor),
 new Territory('kamchatka', hoverColor),
 new Territory('siberia', hoverColor),
 new Territory('ural', hoverColor),
 new Territory('afghanistan', hoverColor),
 new Territory('middle_east', hoverColor),
 new Territory('india', hoverColor),
 new Territory('siam', hoverColor),
 new Territory('china', hoverColor),
 new Territory('mongolia', hoverColor),
 new Territory('irkutsk', hoverColor),
 new Territory('ukraine', hoverColor),
 new Territory('southern_europe', hoverColor),
 new Territory('western_europe', hoverColor),
 new Territory('northern_europe', hoverColor),
 new Territory('egypt', hoverColor),
 new Territory('east_africa', hoverColor),
 new Territory('congo', hoverColor),
 new Territory('south_africa', hoverColor),
 new Territory('brazil', hoverColor),
 new Territory('argentina', hoverColor),
 new Territory('eastern_united_states', hoverColor),
 new Territory('western_united_states', hoverColor),
 new Territory('quebec', hoverColor),
 new Territory('central_america', hoverColor),
 new Territory('peru', hoverColor),
 new Territory('western_australia', hoverColor),
 new Territory('alberta', hoverColor)
]

export default Territories